/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _NATIVE_CLIENT_INCLUDED
#define _NATIVE_CLIENT_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_novak_sebastian_info_JNIWrapper_loadImageViaJNI(JNIEnv *, jobject,  jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif