/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _NATIVE_CLIENT_INCLUDED
#define _NATIVE_CLIENT_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int JNICALL Java_novak_sebastian_info_ashmem_jni_JNIWrapper_loadImageViaJNI__Landroid_os_MemoryFile_2Ljava_lang_String_2(JNIEnv *, jobject,  jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif